mysite/blog/urls.py
from django.conf.urls import url
import views

from .feeds import LatestPostFeed

urlpatterns = [
    url(r'^$', views.post_list, name= 'post_list'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]{1,2})/(?P<post>[-\w\s*]+)/$',
       view=views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$',views.post_list,name='post_list_by_tag'),
    url(r'^feed/$',LatestPostFeed(), name='post_feed'),
]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView
from django.urls import reverse_lazy
from blog.sitemaps import  PostSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'post':PostSitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^$',RedirectView.as_view(url=reverse_lazy('blog:post_list'))),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, docunment_root=settings.STATIC_ROOT)

mysite/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='publish')
# Create your models here.
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('publish','Publish'),
    )
    title = models.CharField(max_length=250, verbose_name='标题')
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish',verbose_name = '标记')
    author = models.ForeignKey(User,related_name='blog_posts',verbose_name= '作者')
    body = models.TextField(verbose_name='内容')
    publish = models.DateTimeField(default=timezone.now(),verbose_name='发布时间')
    created = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    updated = models.DateTimeField(auto_now=True,verbose_name='更新时间')
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft',verbose_name='状态')
    tags = TaggableManager()
    objects = models.Manager()
    published = PublishedManager()
    class Meta:
        ordering = ['-publish']
        verbose_name = '文章'
        verbose_name_plural = '文章'
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])  # .../blog/2017/11/4/(slug)

class Comment(models.Model):
    post = models.ForeignKey(Post,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
        verbose_name_plural='评论'
        verbose_name='评论'

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

mysite/blog/forms.py
# -*- coding:utf-8 -*-
from django import forms
from .models import Comment
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

'''
class CommentForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
 '''
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': "名字",}),
            'email':forms.TextInput(attrs={'placeholder': "邮件"}),
            'body': forms.Textarea(attrs={'placeholder': '请留下您的评论'})
        }

mysite/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Post,Comment
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
# Create your views here.
"""
def post_list(request):
    object_list = Post.objects.all()
    paginator = Paginator(object_list,2) #3篇文章为一页
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = Paginator.page(paginator.num_pages)
    return render(request,
                  'list.html',
                  {'posts':posts,
                   'page':page})

class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'list.html'
    tag = None
"""

def post_list(request, tag_slug=None):
    object_list = Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list,2)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
        page = 1
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
        page = paginator.num_pages
    return render(request,'list.html',{'page':page,
                                       'posts':posts,
                                       'tag':tag })



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                    status='publish',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.all().filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'mysite/detail.html', {'post':post,
                                                  'comments':comments,
                                                  'new_comment':new_comment,
                                                  'comment_form':comment_form,
                                                  'similar_posts':similar_posts})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}({}) recommends you reading "{}" '.format(cd['name'],cd['email'],post.title)
            message = 'Read "{}" at {} \n\n{}\'s comments: {}'.format(post.title,post_url,cd['name'],cd['comments'])
            send_mail(subject,message,'15858830567m@sina.cn',[cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'share.html',{'post':post,
                                         'form':form,
                                         'sent':sent})

mysite/templates/base.html
<!DOCTYPE html>
{% load blog_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%  block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <link href="{% static "css/detail.css"%}" rel="stylesheet">
</head>
<!--
        quu..__
         $$$b  `---.__
          "$$b        `--.                          ___.---uuudP
           `$$b           `.__.------.__     __.---'      $$$$"              .
             "$b          -'            `-.-'            $$$"              .'|
               ".                                       d$"             _.'  |
                 `.   /                              ..."             .'     |
                   `./                           ..::-'            _.'       |
                    /                         .:::-'            .-'         .'
                   :                          ::''\          _.'            |
                  .' .-.             .-.           `.      .'               |
                  : /'$$|           .@"$\           `.   .'              _.-'
                 .'|$u$$|          |$$,$$|           |  <            _.-'
                 | `:$$:'          :$$$$$:           `.  `.       .-'
                 :                  `"--'             |    `-.     \
                :##.       ==             .###.       `.      `.    `\
                |##:                      :###:        |        >     >
                |#'     `..'`..'          `###'        x:      /     /
                 \                                   xXX|     /    ./
                  \                                xXXX'|    /   ./
                  /`-.                                  `.  /   /
                 :    `-  ...........,                   | /  .'
                 |         ``:::::::'       .            |<    `.
                 |             ```          |           x| \ `.:``.
                 |                         .'    /'   xXX|  `:`M`M':.
                 |    |                    ;    /:' xXXX'|  -'MMMMM:'
                 `.  .'                   :    /:'       |-'MMMM.-'
                  |  |                   .'   /'        .'MMM.-'
                  `'`'                   :  ,'          |MMM<
                    |                     `'            |tbap\
                     \                                  :MM.-'
                      \                 |              .''
                       \.               `.            /
                        /     .:::::::.. :           /
                       |     .:::::::::::`.         /
                       |   .:::------------\       /
                      /   .''               >::'  /
                      `',:                 :    .'
                                           `:.:'
                          皮卡丘保佑, 代码无BUG
-->

<body>
   <div id="content">
       {% block content %}
       {% endblock %}
   </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog. I've written {% total_posts %} posts so far</p>
        <p><a href="{% url "blog:post_feed" %}">Subscribe to mt RSS</a></p>
        <h3>Latest Posts</h3>
        {% show_latest_posts %}
        <h3>Most comments posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

mysite/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/templates/list.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %}没问题的博客{% endblock %}

{%  block content %}
    <h1>My Blog</h1>
    {%  for post in posts %}
        <h2>
            <a href='{{ post.get_absolute_url }}'>
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
        Tags:
        {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                {{ tag.name }}
            </a>
            {% if not forloop.last %},{% endif %}
        {% endfor %}
    </p>
        <p class="date">
            发布时间：{{ post.publish }}   作者： {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords:30}}
    {% endfor %}
    <h2>{{ page }}</h2>
    {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/templates/mysite/detail.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>
    <h2>Similar posts</h2>
        {% for post in similar_posts %}
            <p>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </p>
        {% empty %}
            There are no similar posts yet.
        {% endfor %}
    {% with comments.count as total_comments %}
        <h2 id="salad">
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

mysite/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
        <span class="current">
        页码：{{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>

mysite/templates/share.html
{% extends 'base.html' %}

{% block title %}Share a Post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was sucessfully sent to {{ cd.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {% for field in form %}
                <div>
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}